In [1]:
print('hello')

hello


张量表示一个由数值组成的数组，这个数组可能有多个维度。具有一个轴的张量对应数学上的向量；具有两个轴的张量对应数学上的矩阵，我们可以使用arrange创建一个行向量x，这个行向量包含0开始的前12个整数。张量中的每个值都称为张量的*元素*

In [2]:
import torch

x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

求张量中的元素总数，即形状的所有元素乘积

In [3]:
x.numel()

12

改变一个张量的形状而不改变元素数量和元素值，可以调用reshape函数，例如加你个张量x形状为(12,)的行向量转换成形状为(3,4)的矩阵，虽然形状发生了改变，但其元素值并没有变，**通过改变张量的形状，张量的大小不会改变**

In [7]:
X=x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

如果我们的形状是(高，宽)那么知道宽度后，高度会被自动计算得出，例如上面的例子，为了获得一个3行的矩阵，我们手动指定了它有3行4列，不过我们看通过-1来调用自动计算出维度，即x.reshape(-1,4)或x.reshape(3,-1)取代上面的代码.
有时，我们希望使用全0，1或者其它常量，或者从待定分布中随机采样的数字来初始化矩阵，我们可以创建一个形状为(2,3,4)的张量，将其中所有元素都设置为0

In [4]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [6]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

有时我们想通过从某个特定的概率分布中随机采样来得到张量中的每个元素的值，以下代码创建一个形状为(3,4)的张量。其中每个元素都从均值为0、标准差为1的标准高斯分布(正态分布)随机采样

In [3]:
torch.randn(3,4)

tensor([[ 1.7250,  0.3667, -0.9757,  0.0090],
        [-1.4047, -0.4993, -0.6668,  0.2680],
        [ 0.9221, -1.8597,  1.0638,  0.1564]])

我们还可以通过提供包含数值的python列表，来为所需张量中的每个元素赋予确定值。在这里，最外层的列表对应于轴0，内层的列表对应于轴1

In [5]:
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

### 2.1.2 运算符
对于将两个数组作为输入的函数，按元素运算将二元运算符应用于两个数组中的每个对应位置的对应元素，我们可以基于任何从标量到标量的函数来创建按元素函数。
在数学表示法在中，通过符号$f: \mathbb{R} \rightarrow \mathbb{R} $ 来表示一元标量运算符(只接收一个输入)，这意味着任何实数(R)映射到另一个实数。同样外面通过符号$ f: \mathbb{R}, \mathbb{R} \rightarrow \mathbb{R} $表示二元标量运算符，意味着该函数接收两个输入，产生一个输出。给定同一形状的任意两个向量$\mathbf{u} $和$\mathbf{v}$和二元运算符$f$,我们可以得到向量$ \mathbf{c} = F(\mathbf{u},\mathbf{v})$.具体计算方法是$ c_i \gets f(u_i, v_i) $，其中$ c_i、u_i $和$ v_i $分别是向量$c、u$和$v$中的元素。在这里，我们可以通过标量函数升级为按元素向量运算来生产向量值$ F: \mathbb{R}^d, \mathbb{R}^d \rightarrow \mathbb{R}^d $.
对于任意具有相同形状的张量，常见的标准算数运算符(+、-、*、/和**）都可以被升级为按元素运算。我们可以在同一形状的任意两个张量上调用按元素操作。下面例子中，我们使用**逗号**来表示一个具有5个元素的元组，其中**每个元素都是按元素操作的结果**。

In [6]:
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
x + y,x - y,x * y,x/y,x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

按元素的方式可以应用更多的计算，包括求幂

In [8]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

除上之外，我们还可以执行线性代数运算，包括向量点积和矩阵乘法。我们也可以把多个张量连结到一起，把它们端对端地叠起来形成个更大的张量。我们只需要提供张量列表，并给出沿哪个轴连结，下面例子演示，沿着行(轴-0，形状的第一个元素)和按列(轴-1，形状的第二个元素)连结两个矩阵时发生的情况，我们可以看到，第一个输出张量的轴-0长度(6)是两个输入张量轴-0长度的在总和；第二个输出张量的轴-1长度(8)，是两个输入张量轴-1长度的总和.

In [10]:
X = torch.arange(12,dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

有时，我们想通过*逻辑运算符*构建二元张量，以X == Y为例对于每个位置，如果X和Y在该位置相等，则新张量中相应项的值为1，这意味着逻辑语句X == Y在该位置处为真，否则该位置为0

In [12]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

对张量中的所有元素进行求和，会产生一个单元素张量

In [13]:
X.sum()

tensor(66.)

### 2.1.3 广播机制
上面部分中，我们看到了如何在相同形状的两个张量上执行按元素操作。在某些情况下，即使形状不同，我们任然可以通过调用*广播机制*，来执行按元素操作，这种机制的工作方式如下:
1. 通过适当复制元素来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状；
2. 对生成的数组执行按元素操作
在大多数情况下，我们将沿着数组中长度为1的轴进行广播；如下例子，a和b分别是3x1和1x2矩阵，我们将两个矩阵广播为一个更大的3x2矩阵，矩阵a复制列，矩阵b复制行，然后再按元素相加

In [15]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b,a + b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]),
 tensor([[0, 1],
         [1, 2],
         [2, 3]]))

### 2.1.4 索引和切片
最后一个元素索引是-1，和python差不多，如下例子可直观表示

In [17]:
X[-1],X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

除读取之外，我们还可以通过指定索引来讲元素写入矩阵

In [20]:
X[1,2] = 12
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 12.,  7.],
        [ 8.,  9., 10., 11.]])

为多个元素赋值*相同*的值,只需要索引所有元素，然后为他们赋值。如下所示[0:2,:]访问第一行和第二行，其中":"代表沿轴1(列)的所有元素,因此，X[0:2, :] 就表示选择了矩阵 X 中的前两行的所有列。

In [28]:
X[0:2] = 99
X

tensor([[99., 99., 99., 99.],
        [99., 99., 99., 99.],
        [ 8.,  9., 10., 11.]])

### 2.1.5 节约内存
我们用Y = X + Y，我们讲取消引用Y指向的张量，而是指向新分配的内存处的张量。
下面例子中，用python的id()函数演示，它给我们提供了内存中引用对象的确切地址，运行 Y = X + Y后我们发现id(Y)指向另一个地址，因为python首先计算Y + X,为结果分配新的内存，然后使Y指向内存中的这个新位置

In [29]:
before = id(Y)
Y = Y + X
id(Y) == before

False

我们可以使用切片表示法将操作的结果分配给先前分配的数组，例如Y[:] = <expression>,为了说明这点，我们首先创建一个新的矩阵z，其形状与另一个Y相同，使用zeros_like来分配一个全0的块

In [31]:
Z = torch.zeros_like(Y)
print('id(Z)',id(Z))
Z[:] = X + Y
print('id(Z)',id(Z))

id(Z) 1959056816464
id(Z) 1959056816464


若在后序计算中没有重复使用X，我们也可以使用X[:] = X + Y或X += Y来减少操作的内存开销。

In [32]:
before = id(X)
X += Y
id(X) == before

True

### 2.1.6 转换为其它python对象
将深度学习框架定义的张量转换为Numpy张量(ndarray)相互转换都很容易，torch张量和numpy数组将共享它们的底层内存，就地操作更改也会同时更改另一个张量。

In [34]:
A = X.numpy()
B = torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

将大小为1的张量转换为python标量，可以调用item函数或python内置函数。

In [36]:
a = torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

### 2.1.7 小结
深度学习存储和操作数据的主要接口是张量(n维数组).它提供了各种功能，包括基本数学运算、广播、索引、切片、内存节省和转换成其它python对象。