## 2.3 线性代数

### 2.3.1.标量
标量由只有一个元素的张量表示。 下面的代码将实例化两个标量，并执行一些熟悉的算术运算，即加法、乘法、除法和指数。

In [3]:
import torch
x = torch.tensor(3.0)
y = torch.tensor(2.0)
x + y,x * y, x / y,x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

### 2.3.2.向量
向量可以被视为标量值组成的列表。 在数学表示法中，向量通常记为粗体、小写的符号
人们通过一维张量表示向量。一般来说，张量可以具有任意长度，取决于机器的内存限制。我们可以使用下标来引用向量的任一元素

In [4]:
x = torch.arange(4)
x[3]

tensor(3)

#### 2.3.2.1. 长度、维度和形状
向量只是一个数字数组，就像每个数组都有一个长度一样，每个向量也是如此。
向量的长度通常称为向量的维度（dimension）。
与普通的Python数组一样，我们可以通过调用Python的内置len()函数来访问张量的长度。

In [5]:
len(x)

4

当用张量表示一个向量（只有一个轴）时，我们也可以通过.shape属性访问向量的长度。 形状（shape）是一个元素组，列出了张量沿每个轴的长度（维数）。 对于只有一个轴的张量，形状只有一个元素。
向量或轴的维度被用来表示向量或轴的长度，即向量或轴的元素数量。 然而，张量的维度用来表示张量具有的轴数。 在这个意义上，张量的某个轴的维数就是这个轴的长度。

In [6]:
x.shape

torch.Size([4])

### 2.3.3.矩阵
当矩阵具有相同数量的行和列时，其形状将变为正方形； 因此，它被称为方阵（square matrix）。
当调用函数来实例化张量时， 我们可以通过指定两个分量M和N来创建一个形状为MXN的矩阵。

In [7]:
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [8]:
# 转置
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [9]:
B = torch.Tensor([[1,2,3],[2,0,4],[3,4,5]])
B

tensor([[1., 2., 3.],
        [2., 0., 4.],
        [3., 4., 5.]])

In [10]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

### 2.3.4.张量
就像向量是标量的推广，矩阵是向量的推广一样，我们可以构建具有更多轴的数据结构。我们开始处理图像时，张量将变得更加重要，图像以
n维数组形式出现， 其中3个轴对应于高度、宽度，以及一个通道（channel）轴， 用于表示颜色通道（红色、绿色和蓝色）。

In [11]:
x = torch.arange(24).reshape(2,3,4)
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

### 2.3.5.张量算法的基本性质
标量、向量、矩阵和任意数量轴的张量（本小节中的“张量”指代数对象）有一些实用的属性。 例如，从按元素操作的定义中可以注意到，任何按元素的一元运算都不会改变其操作数的形状。 同样，给定具有相同形状的任意两个张量，任何按元素二元运算的结果都将是相同形状的张量。 例如，将两个相同形状的矩阵相加，会在这两个矩阵上执行元素加法。

In [12]:
a = torch.arange(20,dtype=torch.float32).reshape(5,4)
b = a.clone()
a,a+b,a*b

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]),
 tensor([[  0.,   1.,   4.,   9.],
         [ 16.,  25.,  36.,  49.],
         [ 64.,  81., 100., 121.],
         [144., 169., 196., 225.],
         [256., 289., 324., 361.]]))

### 2.3.6.降维


In [13]:
x=torch.arange(4,dtype=torch.float32)
x,x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [14]:
A.shape,A.sum()

(torch.Size([5, 4]), tensor(190))

默认情况下，调用求和函数会沿所有的轴降低张量的维度，使它变为一个标量。 我们还可以指定张量沿哪一个轴来通过求和降低维度。 以矩阵为例，为了通过求和所有行的元素来降维（轴0），可以在调用函数时指定axis=0。 由于输入矩阵沿0轴降维以生成输出向量，因此输入轴0的维数在输出形状中消失。

In [15]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0,A_sum_axis0.shape

(tensor([40, 45, 50, 55]), torch.Size([4]))

指定axis=1将通过汇总所有列的元素降维（轴1）。因此，输入轴1的维数在输出形状中消失。

In [16]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1,A_sum_axis1.shape

(tensor([ 6, 22, 38, 54, 70]), torch.Size([5]))

沿着行和列对矩阵求和，等价于对矩阵的所有元素进行求和

In [17]:
A.sum(axis=[0,1]) # 结果和A.sum()相同

tensor(190)

In [18]:
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
A.mean(),A.sum()/A.numel()

(tensor(9.5000), tensor(9.5000))

计算平均值的函数也可以沿指定轴降低张量的维度

In [19]:
A.mean(axis=0),A.sum(axis=0)/A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

#### 2.3.6.1. 非降维求和


In [20]:
sum_A = A.sum(axis=1,keepdims=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [21]:
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

如果我们想沿某个轴计算A元素的累积总和， 比如axis=0（按行计算），可以调用cumsum函数。 此函数不会沿任何轴降低输入张量的维度。

In [22]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

### 2.3.7.点积
给定两个向量，它们的点积是相同位置的按元素乘积的和

In [24]:
import numpy as np
y = np.ones(4)
x,y,np.dot(x,y)

(tensor([0., 1., 2., 3.]), array([1., 1., 1., 1.]), 6.0)

### 2.3.8.矩阵-向量积
在代码中使用张量表示矩阵-向量积，我们使用mv函数。 当我们为矩阵A和向量x调用torch.mv(A, x)时，会执行矩阵-向量积。 注意，A的列维数（沿轴1的长度）必须与x的维数（其长度）相同。

In [25]:
A.shape,x.shape,torch.mv(A,x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

### 2.3.9.矩阵-矩阵乘法
 在下面的代码中，我们在A和B上执行矩阵乘法。 这里的A是一个5行4列的矩阵，B是一个4行3列的矩阵。 两者相乘后，我们得到了一个5行3列的矩阵。

In [29]:
B = torch.ones(4,3)
torch.mm(A,B)

(tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]))

### 2.3.10.范数
非正式地说，向量的范数是表示一个向量有多大。 这里考虑的大小（size）概念不涉及维度，而是分量的大小。在线性代数中，向量范数是将向量映射到标量的函数$\text{f}$范数听起来很像距离的度量。 欧几里得距离和毕达哥拉斯定理中的非负性概念和三角不等式可能会给出一些启发。 事实上，欧几里得距离是一个$L_{2}$范数:假设n维向量x中的元素是$X_{1}$,....,$X_{n}$,其$L_{2}$范数是向量元素平方和的平方根:$$\|\mathbf{x}\|_2=\sqrt{\sum_{i=1}^nx_i^2}$$,其中，在$L_{2}$范数中常常省略下标2，也就是说$||x||$等同于$||x||_2$。在代码中，我们按如下方式计算向量的$L_{2}$范数。

In [30]:
u = torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

$L_{1}$范数，表示为向量元素的绝对值之和:$$\|\mathbf{x}\|_1=\sum_{i=1}^n|x_i|.$$为了计算$L_{1}$范数，我们将绝对值函数和按元素求和组合起来。

In [31]:
torch.abs(u).sum()

tensor(7.)

矩阵$\mathbf{X}\in\mathbb{R}^{m\times n}$的Frobenius范数（Frobenius norm）是矩阵元素平方和的平方根：$$\|\mathbf{X}\|_F=\sqrt{\sum_{i=1}^m\sum_{j=1}^nx_{ij}^2}.$$Frobenius范数满足向量范数的所有性质，它就像是矩阵形向量的$L_{2}$范数。 调用以下函数将计算矩阵的Frobenius范数。

In [32]:
torch.norm(torch.ones((4,9)))
# 4*9 = 36 √36 = 6

tensor(6.)